/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard/calendar'
import { Route as DashboardCoachRouteImport } from './routes/dashboard/coach'
import { Route as EvolutionIndexRouteImport } from './routes/evolution/index'
import { Route as EvolutionDemoRouteImport } from './routes/evolution/demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/dashboard/calendar',
  path: '/dashboard/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCoachRoute = DashboardCoachRouteImport.update({
  id: '/dashboard/coach',
  path: '/dashboard/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolutionIndexRoute = EvolutionIndexRouteImport.update({
  id: '/evolution/',
  path: '/evolution/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolutionDemoRoute = EvolutionDemoRouteImport.update({
  id: '/evolution/demo',
  path: '/evolution/demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/coach': typeof DashboardCoachRoute
  '/evolution/demo': typeof EvolutionDemoRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/evolution/': typeof EvolutionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/coach': typeof DashboardCoachRoute
  '/evolution/demo': typeof EvolutionDemoRoute
  '/dashboard': typeof DashboardIndexRoute
  '/evolution': typeof EvolutionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/coach': typeof DashboardCoachRoute
  '/evolution/demo': typeof EvolutionDemoRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/evolution/': typeof EvolutionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/privacy'
    | '/dashboard/calendar'
    | '/dashboard/coach'
    | '/evolution/demo'
    | '/dashboard/'
    | '/evolution/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/privacy'
    | '/dashboard/calendar'
    | '/dashboard/coach'
    | '/evolution/demo'
    | '/dashboard'
    | '/evolution'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/privacy'
    | '/dashboard/calendar'
    | '/dashboard/coach'
    | '/evolution/demo'
    | '/dashboard/'
    | '/evolution/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardCoachRoute: typeof DashboardCoachRoute
  EvolutionDemoRoute: typeof EvolutionDemoRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  EvolutionIndexRoute: typeof EvolutionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/dashboard/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/coach': {
      id: '/dashboard/coach'
      path: '/dashboard/coach'
      fullPath: '/dashboard/coach'
      preLoaderRoute: typeof DashboardCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolution/': {
      id: '/evolution/'
      path: '/evolution'
      fullPath: '/evolution/'
      preLoaderRoute: typeof EvolutionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolution/demo': {
      id: '/evolution/demo'
      path: '/evolution/demo'
      fullPath: '/evolution/demo'
      preLoaderRoute: typeof EvolutionDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardCoachRoute: DashboardCoachRoute,
  EvolutionDemoRoute: EvolutionDemoRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  EvolutionIndexRoute: EvolutionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
